import { getCompatibilityForPlant } from "@/lib/plants/compatibility-data";
import type { Plant, PlantCategory } from "@/types/plant";

export type CatalogPlant = Plant & {
  /** Extra names for search (e.g. Korean, synonyms). */
  searchTerms: string[];
};

const TREE_GROWTH_BASE = {
  seedlingHeightM: { min: 0.3, max: 0.5 },
  youngHeightM: { min: 1, max: 3 },
} as const;

function treeGrowth(matureHeightM: number, groundSpreadM: number) {
  return {
    ...TREE_GROWTH_BASE,
    matureHeightM,
    groundSpreadM,
  };
}

const BUY_URLS: Partial<Record<string, string>> = {
  // 로즈팜
  rose: "https://www.rosefarm.shop",
  tulip: "https://www.rosefarm.shop",
  cherry_blossom: "https://www.rosefarm.shop",
  // 우리화훼종묘
  sunflower: "https://www.wooriseed.co.kr",
  daisy: "https://www.wooriseed.co.kr",
  lavender: "https://www.wooriseed.co.kr",
  marigold: "https://www.wooriseed.co.kr",
  petunia: "https://www.wooriseed.co.kr",
  orchid: "https://www.wooriseed.co.kr",
  peony: "https://www.wooriseed.co.kr",
  hydrangea: "https://www.wooriseed.co.kr",
  lily: "https://www.wooriseed.co.kr",
  jasmine: "https://www.wooriseed.co.kr",
  camellia: "https://www.wooriseed.co.kr",
  cosmos: "https://www.wooriseed.co.kr",
  pansy: "https://www.wooriseed.co.kr",
  daffodil: "https://www.wooriseed.co.kr",
  iris: "https://www.wooriseed.co.kr",
  chrysanthemum: "https://www.wooriseed.co.kr",
  lotus: "https://www.wooriseed.co.kr",
  hibiscus: "https://www.wooriseed.co.kr",
  geranium: "https://www.wooriseed.co.kr",
  begonia: "https://www.wooriseed.co.kr",
  zinnia: "https://www.wooriseed.co.kr",
  carnation: "https://www.wooriseed.co.kr",
  poppy: "https://www.wooriseed.co.kr",
};

function entry(
  plant: Omit<Plant, "emoji"> & { emoji: string; searchTerms?: string[] },
): CatalogPlant {
  const { searchTerms = [], ...rest } = plant;
  const terms = [
    ...searchTerms,
    rest.name,
    rest.scientificName ?? "",
  ].filter(Boolean);
  const compat = getCompatibilityForPlant(rest.id);

  // 야채/나무는 심폴, 꽃은 BUY_URLS 매핑
  const buyUrl = rest.buyUrl ?? BUY_URLS[rest.id] ??
    (rest.category === "vegetable" || rest.category === "tree"
      ? "https://www.simpol.co.kr"
      : undefined);

  return {
    ...rest,
    buyUrl,
    goodNeighbors: rest.goodNeighbors ?? compat.goodNeighbors,
    badNeighbors: rest.badNeighbors ?? compat.badNeighbors,
    searchTerms: terms,
  };
}

const VEGETABLE_ENTRIES: CatalogPlant[] = [
  entry({
    id: "tomato",
    name: "Tomato",
    category: "vegetable",
    emoji: "🍅",
    scientificName: "Solanum lycopersicum",
    sun: "full",
    water: "high",
    spreadM: 0.6,
    heightM: 1.2,
    wateringIntervalDays: 2,
    minTempC: 5,
    searchTerms: ["토마토", "tomate"],
  }),
  entry({
    id: "basil",
    name: "Basil",
    category: "vegetable",
    emoji: "🌿",
    scientificName: "Ocimum basilicum",
    sun: "full",
    water: "medium",
    spreadM: 0.3,
    heightM: 0.5,
    wateringIntervalDays: 2,
    minTempC: 10,
    searchTerms: ["바질"],
  }),
  entry({
    id: "carrot",
    name: "Carrot",
    category: "vegetable",
    emoji: "🥕",
    scientificName: "Daucus carota",
    sun: "full",
    water: "medium",
    spreadM: 0.15,
    heightM: 0.3,
    wateringIntervalDays: 3,
    minTempC: 0,
    searchTerms: ["당근"],
  }),
  entry({
    id: "lettuce",
    name: "Lettuce",
    category: "vegetable",
    emoji: "🥬",
    sun: "partial",
    water: "medium",
    spreadM: 0.25,
    heightM: 0.25,
    wateringIntervalDays: 2,
    minTempC: 5,
    searchTerms: ["상추", "lettuce"],
  }),
  entry({
    id: "spinach",
    name: "Spinach",
    category: "vegetable",
    emoji: "🥬",
    sun: "partial",
    water: "medium",
    spreadM: 0.2,
    heightM: 0.2,
    wateringIntervalDays: 2,
    minTempC: 0,
    searchTerms: ["시금치"],
  }),
  entry({
    id: "kale",
    name: "Kale",
    category: "vegetable",
    emoji: "🥬",
    sun: "full",
    water: "medium",
    spreadM: 0.35,
    heightM: 0.4,
    wateringIntervalDays: 3,
    minTempC: -5,
    searchTerms: ["케일"],
  }),
  entry({
    id: "cucumber",
    name: "Cucumber",
    category: "vegetable",
    emoji: "🥒",
    sun: "full",
    water: "high",
    spreadM: 0.5,
    heightM: 0.5,
    wateringIntervalDays: 2,
    minTempC: 10,
    searchTerms: ["오이"],
  }),
  entry({
    id: "pepper",
    name: "Bell Pepper",
    category: "vegetable",
    emoji: "🫑",
    sun: "full",
    water: "medium",
    spreadM: 0.45,
    heightM: 0.7,
    wateringIntervalDays: 2,
    minTempC: 10,
    searchTerms: ["피망", "paprika", "capsicum"],
  }),
  entry({
    id: "zucchini",
    name: "Zucchini",
    category: "vegetable",
    emoji: "🥒",
    sun: "full",
    water: "medium",
    spreadM: 0.8,
    heightM: 0.5,
    wateringIntervalDays: 2,
    minTempC: 10,
    searchTerms: ["주키니", "courgette"],
  }),
  entry({
    id: "onion",
    name: "Onion",
    category: "vegetable",
    emoji: "🧅",
    sun: "full",
    water: "low",
    spreadM: 0.15,
    heightM: 0.35,
    wateringIntervalDays: 4,
    minTempC: -5,
    searchTerms: ["양파"],
  }),
  entry({
    id: "garlic",
    name: "Garlic",
    category: "vegetable",
    emoji: "🧄",
    sun: "full",
    water: "low",
    spreadM: 0.12,
    heightM: 0.3,
    wateringIntervalDays: 5,
    minTempC: -10,
    searchTerms: ["마늘"],
  }),
  entry({
    id: "potato",
    name: "Potato",
    category: "vegetable",
    emoji: "🥔",
    sun: "full",
    water: "medium",
    spreadM: 0.4,
    heightM: 0.6,
    wateringIntervalDays: 3,
    minTempC: 0,
    searchTerms: ["감자"],
  }),
  entry({
    id: "broccoli",
    name: "Broccoli",
    category: "vegetable",
    emoji: "🥦",
    sun: "full",
    water: "medium",
    spreadM: 0.45,
    heightM: 0.5,
    wateringIntervalDays: 3,
    minTempC: 5,
    searchTerms: ["브로콜리"],
  }),
  entry({
    id: "cabbage",
    name: "Cabbage",
    category: "vegetable",
    emoji: "🥬",
    sun: "full",
    water: "medium",
    spreadM: 0.5,
    heightM: 0.35,
    wateringIntervalDays: 3,
    minTempC: 0,
    searchTerms: ["양배추", "배추"],
  }),
  entry({
    id: "pea",
    name: "Pea",
    category: "vegetable",
    emoji: "🫛",
    sun: "full",
    water: "medium",
    spreadM: 0.2,
    heightM: 0.6,
    wateringIntervalDays: 2,
    minTempC: 0,
    needsSupport: true,
    searchTerms: ["완두", "green pea"],
  }),
  entry({
    id: "green_bean",
    name: "Green Bean",
    category: "vegetable",
    emoji: "🫘",
    sun: "full",
    water: "medium",
    spreadM: 0.25,
    heightM: 0.5,
    wateringIntervalDays: 2,
    minTempC: 10,
    needsSupport: true,
    searchTerms: ["강낭콩", "string bean"],
  }),
  entry({
    id: "corn",
    name: "Corn",
    category: "vegetable",
    emoji: "🌽",
    sun: "full",
    water: "medium",
    spreadM: 0.3,
    heightM: 2,
    wateringIntervalDays: 2,
    minTempC: 10,
    searchTerms: ["옥수수", "maize"],
  }),
  entry({
    id: "mint",
    name: "Mint",
    category: "vegetable",
    emoji: "🌿",
    scientificName: "Mentha",
    sun: "partial",
    water: "high",
    spreadM: 0.4,
    heightM: 0.4,
    wateringIntervalDays: 2,
    minTempC: 0,
    searchTerms: ["민트", "박하"],
  }),
  entry({
    id: "parsley",
    name: "Parsley",
    category: "vegetable",
    emoji: "🌿",
    sun: "partial",
    water: "medium",
    spreadM: 0.2,
    heightM: 0.3,
    wateringIntervalDays: 2,
    minTempC: 0,
    searchTerms: ["파슬리", "인분"],
  }),
  entry({
    id: "cilantro",
    name: "Cilantro",
    category: "vegetable",
    emoji: "🌿",
    sun: "partial",
    water: "medium",
    spreadM: 0.2,
    heightM: 0.35,
    wateringIntervalDays: 2,
    minTempC: 5,
    searchTerms: ["고수", "coriander"],
  }),
  entry({
    id: "thyme",
    name: "Thyme",
    category: "vegetable",
    emoji: "🌿",
    sun: "full",
    water: "low",
    spreadM: 0.25,
    heightM: 0.2,
    wateringIntervalDays: 4,
    minTempC: -10,
    searchTerms: ["타임", "백리향"],
  }),
  entry({
    id: "rosemary",
    name: "Rosemary",
    category: "vegetable",
    emoji: "🌿",
    sun: "full",
    water: "low",
    spreadM: 0.4,
    heightM: 0.8,
    wateringIntervalDays: 5,
    minTempC: -5,
    searchTerms: ["로즈마리"],
  }),
  entry({
    id: "eggplant",
    name: "Eggplant",
    category: "vegetable",
    emoji: "🍆",
    sun: "full",
    water: "medium",
    spreadM: 0.5,
    heightM: 0.8,
    wateringIntervalDays: 2,
    minTempC: 15,
    searchTerms: ["가지", "aubergine"],
  }),
  entry({
    id: "pumpkin",
    name: "Pumpkin",
    category: "vegetable",
    emoji: "🎃",
    sun: "full",
    water: "medium",
    spreadM: 1.2,
    heightM: 0.4,
    wateringIntervalDays: 3,
    minTempC: 10,
    searchTerms: ["호박"],
  }),
  entry({
    id: "radish",
    name: "Radish",
    category: "vegetable",
    emoji: "🌱",
    sun: "full",
    water: "medium",
    spreadM: 0.1,
    heightM: 0.2,
    wateringIntervalDays: 2,
    minTempC: 0,
    searchTerms: ["무", "daikon"],
  }),
  entry({
    id: "beet",
    name: "Beet",
    category: "vegetable",
    emoji: "🟣",
    sun: "full",
    water: "medium",
    spreadM: 0.2,
    heightM: 0.35,
    wateringIntervalDays: 3,
    minTempC: 0,
    searchTerms: ["비트", "beetroot"],
  }),
  entry({
    id: "asparagus",
    name: "Asparagus",
    category: "vegetable",
    emoji: "🌱",
    sun: "full",
    water: "medium",
    spreadM: 0.4,
    heightM: 1.2,
    wateringIntervalDays: 3,
    minTempC: -5,
    searchTerms: ["아스파라거스"],
  }),
  entry({
    id: "celery",
    name: "Celery",
    category: "vegetable",
    emoji: "🥬",
    sun: "full",
    water: "high",
    spreadM: 0.25,
    heightM: 0.6,
    wateringIntervalDays: 2,
    minTempC: 5,
    searchTerms: ["셀러리"],
  }),
  entry({
    id: "chard",
    name: "Swiss Chard",
    category: "vegetable",
    emoji: "🥬",
    sun: "full",
    water: "medium",
    spreadM: 0.35,
    heightM: 0.5,
    wateringIntervalDays: 2,
    minTempC: 5,
    searchTerms: ["근대", "chard"],
  }),
  entry({
    id: "leek",
    name: "Leek",
    category: "vegetable",
    emoji: "🧅",
    sun: "full",
    water: "medium",
    spreadM: 0.15,
    heightM: 0.5,
    wateringIntervalDays: 3,
    minTempC: -5,
    searchTerms: ["리크", "대파"],
  }),
  entry({
    id: "sweet_potato",
    name: "Sweet Potato",
    category: "vegetable",
    emoji: "🍠",
    sun: "full",
    water: "medium",
    spreadM: 0.5,
    heightM: 0.3,
    wateringIntervalDays: 4,
    minTempC: 15,
    searchTerms: ["고구마"],
  }),
  entry({
    id: "strawberry",
    name: "Strawberry",
    category: "vegetable",
    emoji: "🍓",
    sun: "full",
    water: "medium",
    spreadM: 0.3,
    heightM: 0.2,
    wateringIntervalDays: 2,
    minTempC: -5,
    searchTerms: ["딸기"],
  }),
];

const FLOWER_ENTRIES: CatalogPlant[] = [
  entry({
    id: "rose",
    name: "Rose",
    category: "flower",
    emoji: "🌹",
    sun: "full",
    water: "low",
    spreadM: 0.5,
    heightM: 1,
    wateringIntervalDays: 3,
    minTempC: -5,
    searchTerms: ["장미"],
  }),
  entry({
    id: "sunflower",
    name: "Sunflower",
    category: "flower",
    emoji: "🌻",
    sun: "full",
    water: "medium",
    spreadM: 0.4,
    heightM: 2,
    wateringIntervalDays: 2,
    minTempC: 5,
    needsSupport: true,
    searchTerms: ["해바라기"],
  }),
  entry({
    id: "lavender",
    name: "Lavender",
    category: "flower",
    emoji: "💜",
    scientificName: "Lavandula",
    sun: "full",
    water: "low",
    spreadM: 0.3,
    heightM: 0.6,
    wateringIntervalDays: 7,
    minTempC: -10,
    searchTerms: ["라벤더"],
  }),
  entry({
    id: "tulip",
    name: "Tulip",
    category: "flower",
    emoji: "🌷",
    sun: "partial",
    water: "low",
    spreadM: 0.2,
    heightM: 0.4,
    wateringIntervalDays: 5,
    minTempC: -5,
    searchTerms: ["튤립"],
  }),
  entry({
    id: "daisy",
    name: "Daisy",
    category: "flower",
    emoji: "🌼",
    sun: "full",
    water: "low",
    spreadM: 0.3,
    heightM: 0.4,
    wateringIntervalDays: 4,
    minTempC: -5,
    searchTerms: ["데이지", "marguerite"],
  }),
  entry({
    id: "marigold",
    name: "Marigold",
    category: "flower",
    emoji: "🌼",
    sun: "full",
    water: "low",
    spreadM: 0.25,
    heightM: 0.35,
    wateringIntervalDays: 4,
    minTempC: 5,
    searchTerms: ["금잔화", "merigold"],
  }),
  entry({
    id: "petunia",
    name: "Petunia",
    category: "flower",
    emoji: "🌸",
    sun: "full",
    water: "medium",
    spreadM: 0.35,
    heightM: 0.25,
    wateringIntervalDays: 3,
    minTempC: 5,
    searchTerms: ["페튜니아"],
  }),
  entry({
    id: "orchid",
    name: "Orchid",
    category: "flower",
    emoji: "🌺",
    sun: "partial",
    water: "low",
    spreadM: 0.2,
    heightM: 0.5,
    wateringIntervalDays: 7,
    minTempC: 15,
    searchTerms: ["난초", "orchid"],
  }),
  entry({
    id: "peony",
    name: "Peony",
    category: "flower",
    emoji: "🌸",
    sun: "full",
    water: "medium",
    spreadM: 0.6,
    heightM: 0.9,
    wateringIntervalDays: 4,
    minTempC: -20,
    searchTerms: ["모란", "牡丹"],
  }),
  entry({
    id: "hydrangea",
    name: "Hydrangea",
    category: "flower",
    emoji: "💐",
    sun: "partial",
    water: "high",
    spreadM: 1,
    heightM: 1.2,
    wateringIntervalDays: 2,
    minTempC: -10,
    searchTerms: ["수국"],
  }),
  entry({
    id: "lily",
    name: "Lily",
    category: "flower",
    emoji: "🪷",
    sun: "full",
    water: "medium",
    spreadM: 0.25,
    heightM: 0.8,
    wateringIntervalDays: 3,
    minTempC: -5,
    searchTerms: ["백합", "lilium"],
  }),
  entry({
    id: "jasmine",
    name: "Jasmine",
    category: "flower",
    emoji: "🤍",
    sun: "full",
    water: "medium",
    spreadM: 0.5,
    heightM: 1,
    wateringIntervalDays: 3,
    minTempC: 5,
    searchTerms: ["재스민", "말린", "jasmine"],
  }),
  entry({
    id: "camellia",
    name: "Camellia",
    category: "flower",
    emoji: "🌺",
    sun: "partial",
    water: "medium",
    spreadM: 0.8,
    heightM: 1.5,
    wateringIntervalDays: 4,
    minTempC: 0,
    searchTerms: ["동백"],
  }),
  entry({
    id: "cosmos",
    name: "Cosmos",
    category: "flower",
    emoji: "🌸",
    sun: "full",
    water: "low",
    spreadM: 0.3,
    heightM: 1,
    wateringIntervalDays: 4,
    minTempC: 5,
    searchTerms: ["코스모스"],
  }),
  entry({
    id: "pansy",
    name: "Pansy",
    category: "flower",
    emoji: "🌸",
    sun: "partial",
    water: "medium",
    spreadM: 0.2,
    heightM: 0.2,
    wateringIntervalDays: 3,
    minTempC: -5,
    searchTerms: ["팬지"],
  }),
  entry({
    id: "daffodil",
    name: "Daffodil",
    category: "flower",
    emoji: "🌼",
    sun: "full",
    water: "low",
    spreadM: 0.15,
    heightM: 0.35,
    wateringIntervalDays: 5,
    minTempC: -10,
    searchTerms: ["수선화", "narcissus"],
  }),
  entry({
    id: "iris",
    name: "Iris",
    category: "flower",
    emoji: "💜",
    sun: "full",
    water: "medium",
    spreadM: 0.25,
    heightM: 0.6,
    wateringIntervalDays: 4,
    minTempC: -10,
    searchTerms: ["붓꽃"],
  }),
  entry({
    id: "chrysanthemum",
    name: "Chrysanthemum",
    category: "flower",
    emoji: "🌼",
    sun: "full",
    water: "medium",
    spreadM: 0.4,
    heightM: 0.6,
    wateringIntervalDays: 3,
    minTempC: -5,
    searchTerms: ["국화", "mum"],
  }),
  entry({
    id: "lotus",
    name: "Lotus",
    category: "flower",
    emoji: "🪷",
    sun: "full",
    water: "high",
    spreadM: 0.8,
    heightM: 0.5,
    wateringIntervalDays: 1,
    minTempC: 15,
    searchTerms: ["연꽃", "lotus"],
  }),
  entry({
    id: "hibiscus",
    name: "Hibiscus",
    category: "flower",
    emoji: "🌺",
    sun: "full",
    water: "medium",
    spreadM: 0.5,
    heightM: 1.5,
    wateringIntervalDays: 3,
    minTempC: 10,
    searchTerms: ["무궁화", "hibiscus"],
  }),
  entry({
    id: "geranium",
    name: "Geranium",
    category: "flower",
    emoji: "🌸",
    sun: "full",
    water: "low",
    spreadM: 0.35,
    heightM: 0.4,
    wateringIntervalDays: 4,
    minTempC: 5,
    searchTerms: ["제라늄"],
  }),
  entry({
    id: "begonia",
    name: "Begonia",
    category: "flower",
    emoji: "🌸",
    sun: "partial",
    water: "medium",
    spreadM: 0.3,
    heightM: 0.3,
    wateringIntervalDays: 3,
    minTempC: 10,
    searchTerms: ["베고니아"],
  }),
  entry({
    id: "zinnia",
    name: "Zinnia",
    category: "flower",
    emoji: "🌸",
    sun: "full",
    water: "low",
    spreadM: 0.25,
    heightM: 0.5,
    wateringIntervalDays: 4,
    minTempC: 5,
    searchTerms: ["백일홍", "zinnia"],
  }),
  entry({
    id: "carnation",
    name: "Carnation",
    category: "flower",
    emoji: "🌸",
    sun: "full",
    water: "medium",
    spreadM: 0.25,
    heightM: 0.5,
    wateringIntervalDays: 3,
    minTempC: 0,
    searchTerms: ["카네이션", "carnation"],
  }),
  entry({
    id: "poppy",
    name: "Poppy",
    category: "flower",
    emoji: "🌺",
    sun: "full",
    water: "low",
    spreadM: 0.2,
    heightM: 0.5,
    wateringIntervalDays: 5,
    minTempC: -5,
    searchTerms: ["양귀비"],
  }),
];

const TREE_ENTRIES: CatalogPlant[] = [
  entry({
    id: "oak",
    name: "Oak Tree",
    category: "tree",
    emoji: "🌳",
    sun: "full",
    water: "low",
    spreadM: 0.5,
    heightM: 15,
    growth: treeGrowth(15, 0.5),
    wateringIntervalDays: 7,
    minTempC: -10,
    searchTerms: ["참나무", "oak"],
  }),
  entry({
    id: "apple",
    name: "Apple Tree",
    category: "tree",
    emoji: "🍎",
    sun: "full",
    water: "medium",
    spreadM: 0.5,
    heightM: 6,
    growth: treeGrowth(6, 0.5),
    wateringIntervalDays: 4,
    minTempC: -5,
    searchTerms: ["사과나무", "apple tree"],
  }),
  entry({
    id: "cherry_blossom",
    name: "Cherry Blossom",
    category: "tree",
    emoji: "🌸",
    sun: "full",
    water: "low",
    spreadM: 0.45,
    heightM: 8,
    growth: treeGrowth(8, 0.45),
    wateringIntervalDays: 5,
    minTempC: -5,
    searchTerms: ["벚꽃", "sakura"],
  }),
  entry({
    id: "bamboo",
    name: "Bamboo",
    category: "tree",
    emoji: "🎋",
    sun: "partial",
    water: "medium",
    spreadM: 0.4,
    heightM: 12,
    growth: treeGrowth(12, 0.4),
    wateringIntervalDays: 3,
    minTempC: 5,
    searchTerms: ["대나무"],
  }),
  entry({
    id: "palm",
    name: "Palm Tree",
    category: "tree",
    emoji: "🌴",
    sun: "full",
    water: "low",
    spreadM: 0.5,
    heightM: 12,
    growth: treeGrowth(12, 0.5),
    wateringIntervalDays: 5,
    minTempC: 10,
    searchTerms: ["야자수"],
  }),
  entry({
    id: "lemon",
    name: "Lemon Tree",
    category: "tree",
    emoji: "🍋",
    sun: "full",
    water: "medium",
    spreadM: 0.4,
    heightM: 4,
    growth: treeGrowth(4, 0.4),
    wateringIntervalDays: 4,
    minTempC: 5,
    searchTerms: ["레몬나무"],
  }),
  entry({
    id: "pine",
    name: "Pine Tree",
    category: "tree",
    emoji: "🌲",
    sun: "full",
    water: "low",
    spreadM: 0.55,
    heightM: 20,
    growth: treeGrowth(20, 0.55),
    wateringIntervalDays: 7,
    minTempC: -20,
    searchTerms: ["소나무", "pine"],
  }),
  entry({
    id: "maple",
    name: "Maple Tree",
    category: "tree",
    emoji: "🍁",
    sun: "full",
    water: "medium",
    spreadM: 0.5,
    heightM: 12,
    growth: treeGrowth(12, 0.5),
    wateringIntervalDays: 5,
    minTempC: -20,
    searchTerms: ["단풍나무", "maple"],
  }),
  entry({
    id: "willow",
    name: "Willow Tree",
    category: "tree",
    emoji: "🌳",
    sun: "full",
    water: "high",
    spreadM: 0.6,
    heightM: 10,
    growth: treeGrowth(10, 0.6),
    wateringIntervalDays: 3,
    minTempC: -15,
    searchTerms: ["버드나무"],
  }),
  entry({
    id: "fig",
    name: "Fig Tree",
    category: "tree",
    emoji: "🌳",
    sun: "full",
    water: "low",
    spreadM: 0.45,
    heightM: 5,
    growth: treeGrowth(5, 0.45),
    wateringIntervalDays: 5,
    minTempC: 5,
    searchTerms: ["무화과나무"],
  }),
  entry({
    id: "olive",
    name: "Olive Tree",
    category: "tree",
    emoji: "🫒",
    sun: "full",
    water: "low",
    spreadM: 0.5,
    heightM: 6,
    growth: treeGrowth(6, 0.5),
    wateringIntervalDays: 7,
    minTempC: 0,
    searchTerms: ["올리브나무"],
  }),
  entry({
    id: "magnolia",
    name: "Magnolia",
    category: "tree",
    emoji: "🌸",
    sun: "full",
    water: "medium",
    spreadM: 0.55,
    heightM: 8,
    growth: treeGrowth(8, 0.55),
    wateringIntervalDays: 5,
    minTempC: -10,
    searchTerms: ["목련", "magnolia"],
  }),
];

export const PLANT_CATALOG: CatalogPlant[] = [
  ...VEGETABLE_ENTRIES,
  ...FLOWER_ENTRIES,
  ...TREE_ENTRIES,
];

export function catalogByCategory(category: PlantCategory): CatalogPlant[] {
  return PLANT_CATALOG.filter((plant) => plant.category === category);
}

export function catalogPlantById(id: string): CatalogPlant | undefined {
  return PLANT_CATALOG.find((plant) => plant.id === id);
}

/** Strip search-only fields for use as a Plant. */
export function toPlant(entry: CatalogPlant): Plant {
  const { searchTerms: _terms, ...plant } = entry;
  void _terms;
  return plant;
}

export const VEGETABLE_PLANTS = catalogByCategory("vegetable").map(toPlant);
export const FLOWER_PLANTS = catalogByCategory("flower").map(toPlant);
export const TREE_PLANTS = catalogByCategory("tree").map(toPlant);
export const SAMPLE_PLANTS = [
  ...VEGETABLE_PLANTS,
  ...FLOWER_PLANTS,
  ...TREE_PLANTS,
];

export function getPlantEmoji(plantId: string): string {
  const plant = PLANT_CATALOG.find((p) => p.id === plantId);
  return plant?.emoji ?? "🌱";
}
